[package]
name = "burgame"
version = "0.1.0"
edition = "2021"

[dependencies]
burengine = { path = "../burengine" }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
as-any = { version = "0.1.0" }
